apiVersion: v1 
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: mysql
  subdomain: mysql-h  # creates DNS record to point to headless service
  hostname: mysql-pod  # to create A records for individual pod