apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  DB_HOST: bX1zWw=
  DB_USER: cm8vdA==
  DB_PASSWORD: cGF34dUk=

# kubectl create secret generic <name> --from-literal=<key>=<value>
# kubectl create secret generic <name> --form-file=<filename>

---
apiVersion: v1 
kind: Pod
metadata:
  name: app-pod
spec:
  containers:
    - name: webapp-color
      image: webapp-color
      ports:
        - containerPort: 8080
      envFrom:
        - secretRef:
          name: app-secret
          